---
title: "Journal Challenge 1"
author: "David Hackenberger"
date: "2020-11-019"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# SALES ANALYSIS & Intro do Tidyverse----

### Load libraries
```{r}
library(tidyverse)
library(readxl)
```
# Data structuring
## Importing Files
```{r}
bikes_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/bikes.xlsx")
bikeshops_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/bikeshops.xlsx")
orderlines_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/orderlines.xlsx")
```

## Examining Data
```{r}
glimpse(bikes_tbl)
glimpse(bikeshops_tbl)
glimpse(orderlines_tbl)
```

## Joining Data
```{r}
bikeshop_orderlines_bikes_joined_tbl <- bikeshops_tbl %>%
  left_join(orderlines_tbl, by = c("bikeshop.id" = "customer.id")) %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id"))
glimpse(bikeshop_orderlines_bikes_joined_tbl)
```

## Wrangling Data
```{r}
bikeshop_orderlines_bikes_wrangled_tbl <- bikeshop_orderlines_bikes_joined_tbl %>%
  # 5.1 separate locations
  separate(col    = location,
           into   = c("city", "state"),
           sep    = ", ") %>%
  # 5.2 clean
  select(-ends_with(".id"),-city,-lat,-lng,-...1,-model,-model.year,-order.line,-frame.material,-weight,-category,-gender,-url) %>%
  # 5.3 Add the total price (price * quantity) 
  mutate(total.price = price * quantity) %>%
  # 5.4 Rename
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

glimpse(bikeshop_orderlines_bikes_wrangled_tbl)
```

# Business Insights
## Sales by State

### Step 1 - Manipulate
```{r}
sales_by_state_tbl <- bikeshop_orderlines_bikes_wrangled_tbl %>%
  # Select columns
  select(state, total_price) %>%
  
  # Grouping by year and summarizing sales
  group_by(state) %>% 
  summarize(sales = sum(total_price)) %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))
glimpse(sales_by_state_tbl)
```

### Step 2 - Visualize
```{r plot_1, fig.width=10, fig.height=7}
sales_by_state_tbl%>%
  
  # Setup canvas with the columns states (x-axis) and sales (y-axis)
  ggplot(aes(x = state, y = sales)) +
  # Geometries
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_text(aes(label = sales_text),angle = 90,hjust="bottom",nudge_y = 100000) + # Adding labels to the bars
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €"),n.breaks = 8, limits = c(0,12000000)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(
    title    = "Revenue per state",
    # Dynamischer Subtitle mit paste Funktion 
    subtitle = paste(sales_by_state_tbl$state[sales_by_state_tbl$sales==max(sales_by_state_tbl$sales)],"has the highest revenue"),
    x = "", # Override defaults for x and y
    y = "Revenue"
  )
```

## Sales by Year and State 
```{r}
library(lubridate)
```

### Step 1 - Manipulate
```{r}
sales_by_year_state_tbl <- bikeshop_orderlines_bikes_wrangled_tbl %>%
  # Select columns and add a year
  select(order_date, total_price, state) %>%
  mutate(year = year(order_date)) %>%
  # Group by and summarize year and main catgegory
  group_by(year, state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

glimpse(sales_by_year_state_tbl)
```
  
### Step 2 - Visualize
```{r plot_2, fig.width=10, fig.height=7}
sales_by_year_state_tbl %>%
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col()+ # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ state)+
  
  # Trendline
  geom_smooth(method = "lm", se = FALSE) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and state",
    subtitle = "North Rhine-Westphalia has the highest upward trend",
    fill = "State" # Changes the legend name
  )

```

# Writing Files

## RDS
```{r}
bikeshop_orderlines_bikes_wrangled_tbl %>% 
  write_rds("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Manipulated_Data/Intro_to_tidyverse/bikeshop_orderlines.rds")
```
