---
title: "Intro to tidyverse"
date: "Nov 23, 2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# SALES ANALYSIS ----

## 1.0 Load libraries ----
```{r}
library(tidyverse)
library(readxl)
```


## 2.0 Importing Files ----
```{r}
bikes_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/bikes.xlsx")
bikeshops_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/bikeshops.xlsx")
orderlines_tbl <- read_excel("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Raw_Data/Intro_to_tidyverse/orderlines.xlsx")
```


## 3.0 Examining Data ----
```{r}
glimpse(bikes_tbl)
glimpse(bikeshops_tbl)
glimpse(orderlines_tbl)
```


## 4.0 Joining Data ----
```{r}
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))
```


## 5.0 Wrangling Data ----
### 5.1 Separate category name
```{r}
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% separate(col    = category,
                                                                        into   = c("category.1", "category.2", "category.3"),
                                                                        sep    = " - ") %>%
  # 5.2 Add the total price (price * quantity) 
  mutate(total.price = price * quantity) %>%
  # 5.3 Reorganize
  select(-...1, -gender) %>%
  # 5.3.2 by pattern
  select(-ends_with(".id")) %>%
  # 5.3.3
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  #5.3.4 Reorder
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  #5.4 Rename
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))
```


## 6.0 Business Insights ----
### 6.1 Sales by Year ----
```{r}
library(lubridate)
```

#### Step 1 - Manipulate
```{r}
sales_by_year_tbl <- bike_orderlines_wrangled_tbl %>%
  
  # Select columns
  select(order_date, total_price) %>%
  
  # Add year column
  mutate(year = year(order_date)) %>%
  
  # Grouping by year and summarizing sales
  group_by(year) %>% 
  summarize(sales = sum(total_price)) %>%
  
  # Optional: Add a column that turns the numbers into a currency format 
  # (makes it in the plot optically more appealing)
  # mutate(sales_text = scales::dollar(sales)) <- Works for dollar values
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_year_tbl
```


#### Step 2 - Visualize
```{r}
sales_by_year_tbl %>%
  
  # Setup canvas with the columns year (x-axis) and sales (y-axis)
  ggplot(aes(x = year, y = sales)) +
  
  # Geometries
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label(aes(label = sales_text)) + # Adding labels to the bars
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  
  # Formatting
  # scale_y_continuous(labels = scales::dollar) + # Change the y-axis. 
  # Again, we have to adjust it for euro values
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by year",
    subtitle = "Upward Trend",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )

```

### 6.2 Sales by Year and Category 2 ----
#### Step 1 - Manipulate
```{r}
sales_by_year_cat_1_tbl <- bike_orderlines_wrangled_tbl %>%
  
  # Select columns and add a year
  select(order_date, total_price, category_1) %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and main catgegory
  group_by(year, category_1) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_year_cat_1_tbl 
```


#### Step 2 - Visualize
```{r}
sales_by_year_cat_1_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = category_1)) +
  
  # Geometries
  geom_col()+ # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ category_1)+
  
  # Trendline
  geom_smooth(method = "lm", se = FALSE) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and main category",
    subtitle = "Each product category has an upward trend",
    fill = "Main category" # Changes the legend name
  )
```


## 7.0 Writing Files ----

### 7.3 RDS ----
```{r}
bike_orderlines_wrangled_tbl %>% 
  write_rds("~/Documents/GitHub/ws20-business-data-science-basics---lab-journal-ckz-dev/Manipulated_Data/Intro_to_tidyverse/bike_orderlines.rds")
```

